name: build-all

on:
  repository_dispatch:
    types: [build-trigger]

jobs:
  build-ubuntu-amd64:
    strategy:
      matrix:
        os: ["impish", "focal"]
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: get_version
        run: |
          GITHUB_REF=${{ github.event.client_payload.ref }}
          echo ::set-output name=VERSION::${GITHUB_REF/\refs/tags\/v/}
          echo ::set-output name=VERSION_ONLY::${GITHUB_REF/v/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get project name
        id: get_project_name
        run: |
          PROJECT=$(cat CMakeLists.txt | grep project | sed 's/project(\(.*\) C CXX)/\1/')
          echo ::set-output name=PROJECT_NAME::${PROJECT}
      - name: Build the builder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ubuntu-amd64.Dockerfile
          load: true
          tags: build-ubuntu-amd64:${{ matrix.os }}
          build-args: |
            UBUNTU_VERSION=${{ matrix.os }}
      - name: Build Package
        run: |
          docker run --rm -v `pwd`:/src -v `pwd`/output:/build build-ubuntu-amd64:${{ matrix.os }} /bin/bash -c 'cmake /src && cmake --build . && cpack . && cp *.deb /output'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debs-ubuntu-amd64-${{matrix.os}}
          path: |
            output/${{ steps.get_project_name.outputs.PROJECT_NAME }}-${{ steps.get_version.outputs.VERSION_ONLY }}-${{ matrix.os }}.deb
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.client_payload.release.upload_url }}
          asset_path: output/${{ steps.get_project_name.outputs.PROJECT_NAME }}-${{ steps.get_version.outputs.VERSION_ONLY }}-${{ matrix.os }}.deb
          asset_name: ${{ steps.get_project_name.outputs.PROJECT_NAME }}-${{ steps.get_version.outputs.VERSION_ONLY }}-${{ matrix.os }}.deb
          asset_content_type:  application/vnd.debian.binary-package 

  publish-release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu-amd64]
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          release_id: ${{ github.event.client_payload.release.id }}
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
